name: Rust

on:
  push:
    branches: [ "tui", "main" ]
  pull_request:
    branches: [ "tui", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Linting
      run: cargo clippy
    - name: Formatting
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
